### ISSUE TITLE
Rename to ObjectTracer?

### ISSUE THREAD

**Issue by st0012** [st0012/object_tracer#80]
`TappingDevice` doesn't convey the idea of the gem very well. But `ObjectTracer` seems to be a very good name for that purpose.

**Comment by benoittgt** [comment]
I agree! :)

**Comment by st0012** [comment]
@benoittgt do you think the gem is ready to be bumped to `1.0` with the name change? or something like `0.7` would be better 🤔

**Comment by st0012** [comment]
I just changed its name to `object_tracer` and published version `1.0.0`, because why not? 😄
